export const config = {
  BASE_URL: "https://api.frejun.ai/api/v1",
  BASE_TIMEOUT_MS: 10000,
  RECORDING_DOWNLOAD_TIMEOUT_MS: 30000,
  RETRY_COUNT: 3,
  MAX_RETRY_DELAY_MS: 2000,
  CALL_CONTROL_RETRY_BASE_DELAY_MS: 300,
  CALL_CONTROL_TIMEOUT_MS: 5000,
  IDEMPOTENCY_KEY_MAX_LEN: 255
};
